appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: oQV5juF93PAf0ISb5luOko3rAh0LluRak+r2LmGpLErQeTNyFG6a9uXRkSfXKBVEpifovp5lQV0zAdA4ZHq/+pDt3gWWEM4WMZr/DLIYtsb3pQyUIrlfiJYDefYq1ad2wS6BgQv0FCWd7KdlmU50DzmqMjxeAI7jtQOKODjCy5ahZgwIcjVTd/aBts6eqnlRQ5nHKHmUDP0ipbduiyonl8Uc9u3aInRYygcuxcoT7vBZ08nFFy6zwls5dO0vSh8eh03mfHq6rqY6ZA43YZMA+awHZr/qDwixrbstkiBlOkB4/DBU1vl1DldEDiGCCH0ZfEQI1P8AiNy3yiSWvq7gLQ/CysX8firsDnVNG3o6Z+0sHfZddDn8ydR71DG9Jb1iXoimUJOR3ZLZxayyKndEqHXSLdRKFKlg0hI+mjV4OTTL+J2WUEOlmcg7DbjvsjUoQfupDYCIIV3Jq9fRS5k5eAiAd+7oIq32XHr+1ssAaRpa3NP9LYUqFnFjeXWJmmFg+UWA/06Uhjd6XFuThxupwq3JVgaErUu2TgM8Hq9FI9XGGIhsgCzLnHwQx7TWRxgfiFKbNpeGLUjBlUsczZQt0yk05XLthUrCYcC+39xKV4ECqGZrfv+htith+TIUWENMSRbaiBZJyAU0OWX+AMlhMg8RGciC6U8x/AsBTfJR8aM=}
